lectia-1: Add repsonive box style
7ewen/css-advanced pull request #1
Opened 2022-11-24 13:38 UTC by 7ewen

2022-11-24 13:56 UTC, alexcracea requested changes

2022-11-24 13:56 UTC, alexcracea commented on scss/layout/_section.scss
> +  border-bottom: #EEEEEE solid;
please add `1px` to the border to make it explicit here and everywhere you use border

2022-11-24 13:56 UTC, alexcracea commented on scss/layout/_section.scss
> +}
Please leave an empty line here and generally at the end of every text file, see how github suggests it?

2022-11-24 13:56 UTC, alexcracea commented on scss/layout/_section.scss
> +  padding-top:30px;
please add space after each colon symbol

2022-11-24 13:56 UTC, alexcracea commented on scss/components/_header.scss
> +.header input#mySearch {
the selector is very specific, you don't need priority of 111 for this one, add a class to the text input to target it easier, or at least use the ID alone `#mySearch {}`

2022-11-24 13:56 UTC, alexcracea commented on index.html
> +    <div class="icons">
Lets enhance the semantics for this - Please use a `<ul>` with 4 `<li>` elements, and wrap an `<a>` around each svg icon, in the future we will make the click action to work correctly with javascript

2022-11-24 13:56 UTC, alexcracea commented on index.html
> +        <span class="title-text">UI Components</span>
I see you want to have them categorised and its good, but if you want to continue with this implementation lets use a more BEM-named class, several examples: `section__category` or `section__eyebrow`

2022-11-25 08:58 UTC, 7ewen commented on scss/layout/_section.scss
> +  border-bottom: #EEEEEE solid;
Done

2022-11-25 09:00 UTC, 7ewen commented on scss/layout/_section.scss
> +}
Done, but unfortunately I didn't see how github suggest it.

2022-11-25 09:00 UTC, 7ewen commented on scss/layout/_section.scss
> +  padding-top:30px;
checked each line and changed, done.

2022-11-25 09:01 UTC, 7ewen commented on scss/components/_header.scss
> +.header input#mySearch {
changed to #mySearch {} alone

2022-11-25 09:16 UTC, 7ewen commented on index.html
> +    <div class="icons">
@alexcracea   That's the most dificult part, I tried to remove <a> cause it's showing clicking spaces between SVG's.  
![Screenshot_14](https://user-images.githubusercontent.com/110491176/203942762-b2690efe-085c-4dc9-aa3b-0904b4c50c16.png)

screen attached. Also the measurements of SVG didn't change.
2nd screen attached.
![measurments](https://user-images.githubusercontent.com/110491176/203943257-9c330884-f584-47c3-9629-0d95581df711.png)

idk why, please help! 🙏

2022-11-25 16:25 UTC, merged