Lectia 4
7ewen/css-advanced pull request #3
Opened 2022-12-01 12:36 UTC by 7ewen

2022-12-01 12:47 UTC, alexcracea requested changes

2022-12-01 12:47 UTC, alexcracea commented on scss/base/_helpers.scss
> +}
These were written during the class here just to provide an example of how to work with section, you don't really need these changes unless you planned your section like that.

Please remove this code if its just a leftover from class, you can save it in notes somewhere to keep it cleaner here

2022-12-01 12:47 UTC, alexcracea commented on scss/components/_filters.scss
> +    object-fit: cover;
filter-box doesn't need all these changes copied here. you have this exact code already written in `.ratio-box` at `scss/layout/_ratio-box.scss`. You only needed to remove width/height from here, then in the HTML you should add the `ratio-box` class to the `filter-box` element, example: 
```
<div class="col-lg-4">
  <div class="filter-box ratio-box filter-box--grayscale">
    <img srcset="images/filter.jpg 1x, images/filter.jpg 2x" src="images/filter.jpg" alt="">
  </div>
</div>
```

2022-12-01 12:47 UTC, alexcracea commented on scss/components/_gradients.scss
> +  }
same comment as for filter-box, please don't duplicate code

2022-12-01 12:47 UTC, alexcracea commented on scss/components/_icons.scss
> +  &:hover {
nice fix, Although I have a suggestion: you could simply add a class to each `<svg>` itself or to the `<li>` instead of grabbing it via child

2022-12-01 12:47 UTC, alexcracea commented on scss/components/_filters.scss
> +.second-ratio {
to use 4:3 and 16:9 you only need the `filter-box filter-box--4-3` and `filter-box filter-box--16-9`

2022-12-01 14:26 UTC, 7ewen commented on scss/base/_helpers.scss
> +}
done

2022-12-01 14:27 UTC, 7ewen commented on scss/components/_gradients.scss
> +  }
done

2022-12-01 14:30 UTC, 7ewen commented on scss/components/_filters.scss
> +    object-fit: cover;
done

2022-12-01 14:30 UTC, 7ewen commented on scss/components/_filters.scss
> +.second-ratio {
done

2022-12-01 15:08 UTC, alexcracea requested changes

2022-12-01 15:08 UTC, alexcracea commented on scss/main.scss
> -@import 'base/helpers';
please revert this line, you still have the file, even if its empty we might use it later

2022-12-01 15:10 UTC, 7ewen commented on scss/main.scss
> -@import 'base/helpers';
done

2022-12-02 14:56 UTC, alexcracea requested changes

2022-12-02 14:56 UTC, alexcracea commented on scss/components/_icons.scss
> +.svg_shadows_green:hover{
this selector lacks a space before `{` bracket

2022-12-02 14:56 UTC, alexcracea commented on scss/main.scss
> +@import 'base/helpers';
Please be careful with the import order. The final CSS output will lay out all styles in the exact order you enumerated the imports. Imagine these all would be `<link>` tags in the HTML head. You need to import breakpoints, variables, reset - everything from base, then everything from layouts and only then everything from components

2022-12-02 15:00 UTC, 7ewen commented on scss/components/_icons.scss
> + filter: drop-shadow(10px -5px 1px rgb(0, 166, 0));
ty, done

2022-12-02 15:02 UTC, 7ewen commented on scss/components/_icons.scss
> +.svg_shadows_green:hover{
done

2022-12-02 15:08 UTC, 7ewen commented on scss/main.scss
> +@import 'base/helpers';
changed, done

2022-12-02 15:38 UTC, alexcracea approved these changes

2022-12-02 15:38 UTC, merged